### ISSUE TITLE
Izabela-next build 25/Win11 Overlay Issues

### ISSUE THREAD

**Issue by Vraxx721** [nature-heart-software/izabela#628]
Have been testing testing legacy izabela and izabela-next client to help a streamer friend.

Noticed that izabella-next build 25 seems to have issues under Win11. 
Seems like toggling it to foreground or back/forth from overlay causes a focus issue. 
UI is visible but nothing responds to inputs.

Izabela legacy build, however doesn't seem to suffer the same issue under Win11.

**Comment by Wurielle** [comment]
Sorry for the late reply, GitHub didn't notify me about new issues.. Is there any particular software running when using Izabela? There shouldn't be any issue with the OS but maybe it's interfering with another software

**Comment by Vraxx721** [comment]
Wasn't really running anything. Tested this on a Win11 Lenovo Laptop. It
looks like bringing up the app with Ctrl-enter the overlay comes up but the
second the mouse is moved focus is lost. Active apps were mostly Discord,
Chrome. nothing graphics intense. I haven't had a chance to stage a VM with
a more stripped down image to see if I can replicate it further.
I noticed the slight red-outline around the app window disappears the
moment the mouse is moved at which point the UI doesn't respond to input.

App behavior is however correct in Windows 10.

--Addison C.

**Comment by Wurielle** [comment]
To add some context, the red boxes represent the hitboxes for the mouse, if the mouse moves inside a box the window becomes focusable meaning mouse inputs will work on the ui. 

You can only type a message when the text input is focused which is known when the dark overlay is present. If the text input is focused, the dark overlay appears on the window where the messenger window is opened to prevent accidental mouse movements after focusing the text input (which basically adds a big red box on the screen). 

If there's mouse movement on another screen or on the egde of the screen, focus will be lost and that's normal behavior. 
The reason behind this choice is that Izabela is an accessibility tool at heart and needs to be always on top no matter what activity the user is doing and clickthrough needs to be toggled in the backend based on mouse position. That's a limitation only solved with the hitbox system. 

If the mouse is moving inside a hitbox and focus is lost however this is a bug, which happens sometimes due to the throttled mouse movement event however this should NOT be a consistent issue.

By default, when pressing `Ctrl + Enter` the text input will be focused and the overlay will be showing and keyboard inputs should work just fine. If the overlay disappeared, that means that either focus was lost due to mouse movement or the app was toggled using the compatibility shortcut which doesn't focus the text input by default due to some limitations. To regain focus, you can click the text input inside the messenger window or if you just want to interact with the app you should be able to just hover your mouse on ui elements normally like any other app.

If you don't encounter the behaviors listed above I would gladly accept a recording of the behaviors you're encountering if you can and I'll investigate the issue shortly!

I hope I was able to clarify some things and thank you for helping with the issue! 😄

**Comment by Vraxx721** [comment]
Appreciate that. I'll see about getting a recording. I can understand the
behavior if I was toggling between primary and secondary monitors or
crossing between virtual displays but yes what I was noticing was that the
system would lose focus even just moving the mouse while it was still
within the the main hitbox. It made even just making Settings adjustments
painful since I had to keep using the Ctrl-Enter shortcut to get the ui to
respond.

--Addison

**Comment by Wurielle** [comment]
I see then there could be an issue somewhere on some setups. 
If you don't mind can you please also share the specs of the device where the issue happens please?

**Comment by Vraxx721** [comment]
Certainly. Just wanted to also say, thank you so much for all the work
you've put in on this application.
I haven't been an active programmer in over 20 years but speech synthesis
was my focus in college and seeing more accessible tools available for
people makes me really happy.

I'll pull together details on the laptop hardware and capture a recording
of the issue and send up. If there's anything log wise I should be pulling
down as well let me know.

**Comment by Wurielle** [comment]
Of course, it's my pleasure! Thank you for the kind words and the support! ❤️ 

I want to update this as a user on discord seems to be having the same problem but I couldn't replicate the issue with a windows 10 and a windows 11 VM.

At the moment, I'm suspecting there's another software interfering with mouse events somehow.

Did you use a specific device to move the mouse like a trackpad, trackpoint, touchscreen or pen?

Do you have any software that modifies Windows in some way and runs in the background like Wallpaper Engine for instance?

**Comment by Vraxx721** [comment]
In the case of my laptop not that I'm aware of. It's a mostly bone stock
Lenovo X1 Carbon that I use for work. so other than their default mouse
drivers there's no other modifications that I loaded.
I agree it almost seems like there's something causing a shift in the focus
area so that it puts izabela back into the background. I still need to load
OBS onto the laptop to see if I can record the behavior in real time. I'll
see if I can disable the track pad and run this off an external logitech
mouse to see if the touchpad itself is just hyper sensitive

**Comment by Wurielle** [comment]
Apparently when the UI was scaled up or down it caused the hitboxes to be miscalculated. It's possible that your laptop has a default zoom on windows which makes all applications match that scale and caused the same issue in Izabela. I pushed a fix for that in alpha-27, let me know if that also fixes your issue!

**Comment by Vraxx721** [comment]
Appreciate the quick turn around on that hotfix.

Can confirm, on my Lenovo x1/Win11 with alpha 27, the issue of focus lock
is resolved. App is behaving consistently with my win10 instance.

Have a great week :)

**Comment by Wurielle** [comment]
Awesome! Thanks for the help and have a great week as well! 😄
